### ISSUE TITLE
unable to set alarm time, as soon as i click on time the app crashes

### ISSUE THREAD

**Issue by contactwajeeh** [SimpleMobileTools/Simple-Clock#203]
here is the log for the same.

```
05-23 06:27:10.957  8077  8077 E AndroidRuntime: FATAL EXCEPTION: main
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Process: com.simplemobiletools.clock, PID: 8077
05-23 06:27:10.957  8077  8077 E AndroidRuntime: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class android.widget.TimePicker
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:803)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:120)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.simplemobiletools.clock.c.b$a.onClick(SourceFile:1)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.View.performClick(View.java:6603)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6576)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.View.access$3100(View.java:780)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26090)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6704)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #51: Binary XML file line #51: Error inflating class android.widget.TextInputTimePickerView
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #51: Error inflating class android.widget.TextInputTimePickerView
05-23 06:27:10.957  8077  8077 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:807)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:880)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:841)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.widget.TimePickerClockDelegate.<init>(TimePickerClockDelegate.java:146)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.widget.TimePicker.<init>(TimePicker.java:141)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.widget.TimePicker.<init>(TimePicker.java:114)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.widget.TimePicker.<init>(TimePicker.java:110)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:803)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:120)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at com.simplemobiletools.clock.c.b$a.onClick(SourceFile:1)
05-23 06:27:10.957  8077  8077 E AndroidRuntime: 	at android.view.View.performClick(View.java:6603)
05-23 06:27:10.957  1779  1779 D Surface : lockCanvas
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6576)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.view.View.access$3100(View.java:780)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26090)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6704)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: Caused by: java.lang.ClassCastException: androidx.appcompat.widget.z cannot be cast to android.widget.EditText
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.widget.TextInputTimePickerView.<init>(TextInputTimePickerView.java:81)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.widget.TextInputTimePickerView.<init>(TextInputTimePickerView.java:71)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	at android.widget.TextInputTimePickerView.<init>(TextInputTimePickerView.java:67)
05-23 06:27:10.958  8077  8077 E AndroidRuntime: 	... 37 more
05-23 06:27:10.960   608  1737 I BufferQueueProducer: [#1](this:0x7a27ff1800,id:60,api:2,p:1779,c:608) queueBuffer: fps=0.69 dur=1453.32 max=1453.32 min=1453.32
05-23 06:27:10.962  1055  1801 W ActivityManager:   Force finishing activity com.simplemobiletools.clock/.activities.MainActivity
05-23 06:27:10.965  1055  8116 W AES     : Exception Log handling...
```

**Comment by tibbi** [comment]
what app version is that? Does the time picker work well in other apps?
